name: crud_practice
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.15.0
  cloud_firestore: 4.8.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

